CREATE TABLE USUARIOS
(
    ID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME  VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE NOT NULL,
    SENHA VARCHAR2(256) NOT NULL
);

CREATE TABLE PARTICIPANTES
(
    ID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME  VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE NOT NULL
);

CREATE TABLE GRUPOS
(
    ID   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL
);

CREATE TABLE GRUPO_PARTICIPANTE
(
    GRUPO_ID        NUMBER NOT NULL,
    PARTICIPANTE_ID NUMBER NOT NULL,
    PRIMARY KEY (GRUPO_ID, PARTICIPANTE_ID),
    CONSTRAINT FK_GRUPO FOREIGN KEY (GRUPO_ID) REFERENCES GRUPOS (ID) ON DELETE CASCADE,
    CONSTRAINT FK_PARTICIPANTE_GRUPO FOREIGN KEY (PARTICIPANTE_ID) REFERENCES PARTICIPANTES (ID) ON DELETE CASCADE
);

CREATE TABLE DESPESAS
(
    ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DESCRICAO  VARCHAR2(255) NOT NULL,
    VALOR      NUMBER(10,2) NOT NULL,
    DATA       DATE   NOT NULL,
    GRUPO_ID   NUMBER NOT NULL,
    PAGADOR_ID NUMBER NOT NULL,
    CONSTRAINT FK_GRUPO_DESPESA FOREIGN KEY (GRUPO_ID) REFERENCES GRUPOS (ID),
    CONSTRAINT FK_PAGADOR FOREIGN KEY (PAGADOR_ID) REFERENCES PARTICIPANTES (ID)
);

CREATE TABLE DESPESA_PARTICIPANTE
(
    DESPESA_ID      NUMBER NOT NULL,
    PARTICIPANTE_ID NUMBER NOT NULL,
    VALOR           NUMBER(10,2) NOT NULL,
    STATUS          VARCHAR2(20) DEFAULT 'PENDENTE',
    PRIMARY KEY (DESPESA_ID, PARTICIPANTE_ID),
    CONSTRAINT FK_DESPESA FOREIGN KEY (DESPESA_ID) REFERENCES DESPESAS (ID) ON DELETE CASCADE,
    CONSTRAINT FK_PARTICIPANTE_DESPESA FOREIGN KEY (PARTICIPANTE_ID) REFERENCES PARTICIPANTES (ID) ON DELETE CASCADE
);
